CREATE TABLE IF NOT EXISTS cash_book (
  id SERIAL PRIMARY KEY,
  entry_date DATE NOT NULL DEFAULT CURRENT_DATE,
  particulars VARCHAR(120) NOT NULL,
  entry_type VARCHAR(20) NOT NULL CHECK (entry_type IN ('income', 'expense')),
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  payment_method VARCHAR(30) NOT NULL DEFAULT 'cash',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS purchases (
  id SERIAL PRIMARY KEY,
  purchase_date DATE NOT NULL DEFAULT CURRENT_DATE,
  party_no VARCHAR(60) NOT NULL DEFAULT '',
  bill_no VARCHAR(60) NOT NULL DEFAULT '',
  item_name VARCHAR(120) NOT NULL,
  quantity NUMERIC(12, 2) NOT NULL CHECK (quantity > 0),
  rate NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (rate >= 0),
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  supplier VARCHAR(120) NOT NULL DEFAULT '',
  payment_method VARCHAR(30) NOT NULL DEFAULT 'cash',
  note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sales (
  id SERIAL PRIMARY KEY,
  sale_date DATE NOT NULL DEFAULT CURRENT_DATE,
  item_name VARCHAR(120) NOT NULL,
  quantity NUMERIC(12, 2) NOT NULL CHECK (quantity > 0),
  rate NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (rate >= 0),
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  customer VARCHAR(120) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS parties (
  id SERIAL PRIMARY KEY,
  party_name VARCHAR(120) NOT NULL,
  phone VARCHAR(40) NOT NULL DEFAULT '',
  opening_debit NUMERIC(12, 2) NOT NULL DEFAULT 0,
  opening_credit NUMERIC(12, 2) NOT NULL DEFAULT 0,
  opening_balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  opening_date DATE NOT NULL DEFAULT CURRENT_DATE,
  balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  party_type VARCHAR(20) NOT NULL CHECK (party_type IN ('customer', 'supplier')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS items (
  id SERIAL PRIMARY KEY,
  item_name VARCHAR(120) NOT NULL,
  category VARCHAR(80) NOT NULL DEFAULT 'General',
  stock INT NOT NULL DEFAULT 0,
  unit_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reminders (
  id SERIAL PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  due_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(20) NOT NULL CHECK (status IN ('pending', 'done')) DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE purchases
  ALTER COLUMN quantity TYPE NUMERIC(12, 2) USING quantity::numeric;

ALTER TABLE purchases
  ADD COLUMN IF NOT EXISTS rate NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE purchases
  ADD COLUMN IF NOT EXISTS party_no VARCHAR(60) NOT NULL DEFAULT '';

ALTER TABLE purchases
  ADD COLUMN IF NOT EXISTS bill_no VARCHAR(60) NOT NULL DEFAULT '';

ALTER TABLE purchases
  ADD COLUMN IF NOT EXISTS payment_method VARCHAR(30) NOT NULL DEFAULT 'cash';

ALTER TABLE purchases
  ADD COLUMN IF NOT EXISTS note TEXT NOT NULL DEFAULT '';

ALTER TABLE purchases
  ALTER COLUMN supplier SET DEFAULT '';

ALTER TABLE sales
  ALTER COLUMN quantity TYPE NUMERIC(12, 2) USING quantity::numeric;

ALTER TABLE sales
  ADD COLUMN IF NOT EXISTS rate NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE parties
  ADD COLUMN IF NOT EXISTS opening_debit NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE parties
  ADD COLUMN IF NOT EXISTS opening_credit NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE parties
  ADD COLUMN IF NOT EXISTS opening_balance NUMERIC(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE parties
  ADD COLUMN IF NOT EXISTS opening_date DATE NOT NULL DEFAULT CURRENT_DATE;
